version: '3.3'
services:
  apollo:
    build: Apollo-2.6.2
    restart: always
    ports:
      - "8888:8080"
    volumes:
      - ./data/jbrowse:/data
      - ./data/postgres-data:/var/lib/postgresql

